"""Count granules by platform

Revision ID: cd7ddf84344c
Revises: 1c8c38951d47
Create Date: 2024-11-25 17:37:20.873221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7ddf84344c'
down_revision = '1c8c38951d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('granule_count', sa.Column('platform', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('granule_count', 'platform')
    # ### end Alembic commands ###
