"""Granule count by platform

Revision ID: ec89745f0bac
Revises: 1c8c38951d47
Create Date: 2024-11-25 18:13:36.964410

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec89745f0bac"
down_revision = "1c8c38951d47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "granule_count_pkey",
        "granule_count",
        "primary",
    )
    op.add_column(
        "granule_count",
        sa.Column(
            "platform",
            sa.String(),
            nullable=False,
            server_default="S2A+S2B",
        ),
    )
    op.create_primary_key(
        "granule_count_pkey",
        "granule_count",
        ["date", "platform"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "granule_count_pkey",
        "granule_count",
        "primary",
    )
    op.drop_column("granule_count", "platform")
    op.create_primary_key(
        "granule_count_pkey",
        "granule_count",
        ["date"],
    )
    # ### end Alembic commands ###
